created and implemented toast notification
PGBSNH19/project-grupp-1-hotel pull request #37
Opened 2020-12-24 14:27 UTC by samirehsani19

God jul (👍 (💯

2020-12-26 10:09 UTC, pirren requested changes
Den här branchen pekar på main istället för development. God jul!

2020-12-28 10:21 UTC, pirren approved these changes

2020-12-28 10:29 UTC, erifredrika approved these changes
Snyggt, äntligen får vi toast 👍

2020-12-28 10:36 UTC, merged

2020-12-28 10:36 UTC, singelmamma approved these changes

2020-12-28 10:36 UTC, MirkoPralica approved these changes
GG(Gör Gött) Samir