Added Dtos and Models for Room and Booking
PGBSNH19/project-grupp-1-hotel pull request #7
Opened 2020-12-15 15:48 UTC by robotdostopif

2020-12-15 15:57 UTC, pirren approved these changes

2020-12-15 15:58 UTC, singelmamma approved these changes

2020-12-16 08:07 UTC, merged

2020-12-16 08:08 UTC, MirkoPralica approved these changes
Noice

2020-12-16 08:11 UTC, samirehsani19 requested changes
data validation saknas, just nu kan man ange alla möjliga värde till de olika variabler

2020-12-16 08:13 UTC, erifredrika reviewed
Modellerna och DTO:erna ser bra ut. 👍

2020-12-16 08:13 UTC, erifredrika commented on Hotel.Server/Models/Booking.cs
> +	    public int Id { get; set; }
Pytte lite mycket indentering bara :p